### ISSUE TITLE
Repeatable jobs in bull cause crash.

### ISSUE THREAD

**Issue by adjenks** [bee-queue/arena#150]
I'm not sure why this ticket was closed: https://github.com/bee-queue/arena/issues/43
It seems to still be an issue.
I created one repeatable job as a 'hello world' and it crashed with the same error
`TypeError: Cannot read property 'name' of undefined`

**Comment by Vinhal** [comment]
If you are using docker image, the released version on mixmaxhq directory is old . Try this one https://hub.docker.com/r/odlevakp/arena

**Comment by adjenks** [comment]
@Vinhal Why is this version not in the README?

**Comment by skeggse** [comment]
Thanks for the report. If this is still a problem, you could help us understand the problem by posting a [reprex](https://stackoverflow.com/help/minimal-reproducible-example) - something self-contained that we can use to dig in. Otherwise, we don't have much to go on.

I tried using bull and creating a simple repeatable job, and didn't see any errors in arena when viewing the job.

```js
queue.add('test', { foo: 'bar' }, { repeat: { every: 10000, limit: 100 } });
```

**Comment by adjenks** [comment]
@skeggse Yes, it's probably fine now. I was using the mixmaxhq/arena docker image posted in the README and it was out of date at the time. It's probably working now, considering it says it was updated 20 hours ago and I made this a year ago. Thank you for checking.

**Comment by adjenks** [comment]
I never did use the docker image that Vinhal posted because it wasn't recommended by the README here so I didn't trust it.
