### ISSUE TITLE
Remote connection not working with BullMQ 

### ISSUE THREAD

**Issue by grapevineai** [bee-queue/arena#299]
Seems like redis connection is not used for BullMQ. I have tried the following:

```
const Arena = require('bull-arena');
const { Queue } = require('bullmq');

const arena = Arena({
    BullMQ:Queue,
    queues: [
        {
            name: "myQueue",
            hostId: "My Queue",
            prefix: 'myPrefix',
            type: 'bullmq',
            redis: {
                port: '6379',
                host: '10.56.32.98',
                password: 'P@ssw0rd',
            }
        }
    ]
},
{
    basePath: '/arena',
    disableListen: true
});

app.use('/', arena);
```

But arena tries to connect to Redis at 127.0.0.1:6379

**Comment by yigitkurtcu** [comment]
I have the same problem.

**Comment by skeggse** [comment]
Please confirm you are on `v3.6.1`.

**Comment by yigitkurtcu** [comment]
Yes, I am trying with the versions below.

 **"bull": "^3.20.0",
 "bull-arena": "^3.6.1"**

**Comment by yigitkurtcu** [comment]
I guess the problem is here
**https://github.com/bee-queue/arena/blob/fcd1b61af0166878a09e111e3fce741529b5dd81/src/server/queue/index.js#L102**

BullMQ constructor does not accept parameter object like this. Redis options should be given as one of the following.

**'redis: //127.0.0.1: 6379' 
{redis: {port: 6379, host: '127.0.0.1', password: 'foobared'}}**

**Comment by grapevineai** [comment]
@skeggse Seems like I was using an outdated version!

**Comment by shahana-aym** [comment]
Facing the same issue.
